apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-foyer-deployment
  labels:
    app: tp-foyer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-foyer-app
  template:
    metadata:
      labels:
        app: tp-foyer-app
    spec:
      containers:
      - name: mysqldb
        image: mysql:8.3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "tpfoyer_db"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

      - name: tp-foyer
        image: alachebil/tp-foyer:1.0.0
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8089
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8089
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: tp-foyer-app-service
spec:
  selector:
    app: tp-foyer-app
  ports:
    - name: http-port
      protocol: TCP
      port: 8089
      targetPort: 8089
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
